// Writes public/sw.js from the cache policy and the worker glue. Runs before
// every `next build` (the `prebuild` npm script). The version changes on every
// build, so each deploy ships a new worker that clears the old caches.
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { renderServiceWorker } from '../core/pwa/renderServiceWorker.js'

const commit = () => {
    if (process.env.VERCEL_GIT_COMMIT_SHA) return process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 12)
    try {
        return execSync('git rev-parse --short=12 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
    } catch {
        return 'local'
    }
}

const version = `${commit()}-${Date.now().toString(36)}`
const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')
const source = renderServiceWorker({
    policySource: read('../core/pwa/cachePolicy.js'),
    glueSource: read('./sw/glue.js'),
    version,
})

writeFileSync(new URL('../public/sw.js', import.meta.url), `// Generated by scripts/build-sw.mjs. Don't edit.\n${source}`)
console.log(`public/sw.js written (version ${version})`)
